### ISSUE TITLE
Remove the - -- using https://www.hn-reader.com line

### ISSUE THREAD

**Issue by mtmail** [hn-reader/public#10]
HN users don't like signatures or ads in every comment. If that is part of the software it will only back-fire

![image](https://github.com/hn-reader/public/assets/3727288/25677b8b-24f9-4186-b3d0-7fc02fad5931)
![image](https://github.com/hn-reader/public/assets/3727288/6734f6d9-607d-4354-8694-a301fe9c5504)

**Comment by chief-nerd** [comment]
haha I knew this would come ... so there is checkbox in the app to "disable" that behaviour.
And if it really makes everyone unhappy: happy to take it out completely.

![Screenshot 2024-05-22 at 21 49 32](https://github.com/hn-reader/public/assets/9266151/ec023a47-c317-4e01-9727-737f4d775f6a)

**Comment by chief-nerd** [comment]
ok more people are writing me ... taking this out.

**Comment by chief-nerd** [comment]
Will be deployed as v0.4.9 - already online on web, on ios and android when google and apple approve the new version.
